### ISSUE TITLE
Simpler Alternatives for Template Operators in eZ Publish Legacy

### ISSUE THREAD

**Issue by brookinsconsulting** [donaldinou/ezextrafeatures#3]
Hello @donaldinou 

We stumbled upon your ezpublish based extension repository on GitHub recently and wanted to share with you some thoughts.

First, a big thank you for sharing your extension with others!

After a brief review of your template operator function documentation (pdf) we thought we would point out that the features your using are very similar to the well known classic template operator solution the 'wrap operator' which has a usage syntax very similar to your own. https://github.com/brookinsconsulting/wrapoperator 

But we feel compelled to point out that their is a simpler and easier to use way to create template operators today (the wrap operator being very very old in it's design). Today we use the OWSimpleOperator extension where we used to use the 'wrap operator' or custom template operators in the past. We use the OWSimpleOperator because it's much simpler to use and to expose php functions which require more than 1 parameter (a limitation in the PHP Function support built into eZ Publish's Template layer).

https://github.com/Open-Wide/OWSimpleOperator

While we don't expect you to stop your great work (kudos for your recent repo updates / activity) we did want to share the 'OWSimpleOperator' solution with you in the hopes that you might try making use of it, perhaps for fun at first and learn how much more powerful it is than your current approach, more flexible and much simpler to use in actual template usage.

https://github.com/Open-Wide/OWSimpleOperator/blob/master/doc/INSTALL.md#step-5--use-it-in-your-template

Best wishes!

Cheers,
Brookins Consulting

**Comment by donaldinou** [comment]
Thanks for your compliments. Unfortunately, this extension is not actively maintained. It is an old extension for eZPublish Legacy and I only fix any issues in order to keep this project as clean as possible.
On other hand, the goal of this extension was not only to provide php template operators. The module was made in order to provide some additionnal stuff for most of eZPublish v4 projects. Also I'm not pretty sure that you can call static object method in both of wrapoperator or owsimpleoperator.
But, if we can that's great, and if not it will be a great feature to add :)
In order to promote your work I can add a link to the OWSimpleOperator in the description of this one

Cheers

**Comment by brookinsconsulting** [comment]
Hello @donaldinou 

Thank you for your quick response! I understand what you say about your repository.

I wanted to comment that with OWSimpleOperator you can call static class functions which are provided by whitelist ini settings, Re: https://github.com/Open-Wide/OWSimpleOperator/blob/master/doc/INSTALL.md#step-4--register-your-operator-or-function

I welcome your offer to add a link to OWSimpleOperator in the description of this one :+1: 

Thank you for your continued support!

Cheers,
Brookins Consulting
